### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by CwaUseRu** [p-yukusai/PyWall#19]
After installing the program, it does not work, giving an error. A screenshot is attached.

Windows 11 22H2
![image](https://user-images.githubusercontent.com/73092520/233513033-1044f87d-9543-4a90-85c7-ec50e7ed10c6.png)

**Comment by CwaUseRu** [comment]
1.5 last working build

**Comment by CwaUseRu** [comment]
z

**Comment by CwaUseRu** [comment]
But on 1.5 version didn't work Contect Menu. Error log: 
root - ERROR - Runtime error is "(OSError(9, 'Bad file descriptor'),)", see full traceback bellow: 
 
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "src\config.py", line 253, in validateConfig
    modifyConfig("DEBUG", "version", default_file.get("DEBUG", "version")["version"])
  File "src\config.py", line 143, in modifyConfig
    print("Variable modified")
OSError: [Errno 9] Bad file descriptor

**Comment by p-yukusai** [comment]
Hello! 
It seems that, for whatever reason, shell32 detects your current documents folder to be on the location "E:\\Documents", folder which doesn't seem to exist by the looks of it.
Version 1.5 had a bug regarding printing certain characters that was fixed later on, so that's what you're getting.
I'll make it so PyWall writes to the C drive in the public users directory if it catches a FileNotFoundError, thanks for the report.

**Comment by p-yukusai** [comment]
I've uploaded a new version, please tell me if this fixes your issue.
https://github.com/p-yukusai/PyWall/releases/tag/v1.7.2

**Comment by CwaUseRu** [comment]
Damn. Thank you very much for the answer. I found out what the problem was. I have safe folders enabled in Windows Defender, which affected the work. Who faced this problem: Windows Defender has a protection log in which you can add exceptions.
