### ISSUE TITLE
Flashing cmd consoles that could cause a seizure

### ISSUE THREAD

**Issue by AndreasRoither** [p-yukusai/PyWall#6]
First of all, great work, I quite like this app! It helps me a out a lot!

**Describe the bug**
If multiple .exe files are located in a folder and each one is deactivated/activated, a console for each .exe is started. If there are a ton of .exe files this produces quite a lot of consoles. Luckily I'm not epileptic otherwise this would have caused a seizure for sure. Granted my use case is a bit extreme as I have 30+ .exe files in the folder I want to block but nevertheless, this could pose a significant problem. Also from a technical standpoint, it's better to only issue one console if possible.

**To Reproduce**
1. Have a ton of .exe files in a folder
2. Disable internet access for folder

**Expected behavior**
The ideal case would be that every command is run in just one console.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Education
 - Version	10.0.22000 Build 22000

**Additional context**
There are multiple ways to do it, a python module called `subprocess` or `os` ([Example Blog Post](https://datatofish.com/command-prompt-python/)) could be used, or simply the `&&` operator, or maybe you could even create an executeable file and paste every command in there and start it like that. The choice is yours! If you have any further questions, please reach out!

**Comment by p-yukusai** [comment]
Why thank you!
I'll check it out and fix it soon, glad this small app could prove of use to you 😄

**Comment by p-yukusai** [comment]
Fixed in commit [0a39e8a](https://github.com/p-yukusai/PyWall/commit/0a39e8a976f2535a2f4a3011304beb6d6e5329be).
Thanks for liking and using PyWall 😃 
If you happen to find any other bugs or have suggestions to improve my software further please let me know!

<details>
<summary>Summary of the changes</summary>

- Replaced all of the old os.system functions to subprocess.call, this makes it so the console never really shows up!
- Added a regkey to make the PyWall icon show up in the context menu
- Removed unused dependency "pyqt5custom" since it doesn't work when run as admin
- Version bump
</details>
